### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by albertodeago** [asvae/vue-book#15]
I think there is something wrong with the link pointed by the Demo in the readme. It's pointing to 'http://vue-book-demo.asva.by/#/Demo/ContactComponent.vue'

Or is it only a Demo visible by installing the project locally?

**Comment by asvae** [comment]
@albertodeago No. Should work online o.o. Thanks for pointing out. I'll fix in a moment.

**Comment by asvae** [comment]
Added the one for old version. Url is http://vue-book.asva.by/#/Demo.
