### ISSUE TITLE
🐁 Make it work without router

### ISSUE THREAD

**Issue by asvae** [asvae/vue-book#22]
We shouldn't break without one, right?

- [x] Should allow to use several instances on same page.
- [x] All data should be component specific (search is shared at the moment)
- [x] Add docs

**Comment by davidmoshal** [comment]
We only use router for our vue-book, not our production app, but this hasn't caused any problems.

Additionally if we want to combine many components on one page, then we simply create another demo component with a couple of divs or a table, wrapping the other components.
ie: we let Vue composition handle that problem.
