### ISSUE TITLE
🦋 Clear search button

### ISSUE THREAD

**Issue by davidmoshal** [asvae/vue-book#33]
button (x) to clear the search bar.

**Comment by asvae** [comment]
That's perfectly reasonable. 

(x) button should clear input, then focus on it.

**Comment by asvae** [comment]
Up in `0.1.0-alpha.13`

![image](https://user-images.githubusercontent.com/5394573/52540232-6ee08e80-2d98-11e9-8545-7f8a064b9e07.png)
